---

-  hosts: all
   become: true
   tasks:

     - name: update repo cache (CentOS)
       tags: always
       dnf:
         update_only: yes
         update_cache: yes
       when: ansible_distribution == "CentOS"

     - name: update repo cache (Ubuntu)
       tags: always
       apt:
         update_cache: yes 
         changed_when: false
       when: ansible_distribution == "Ubuntu"









       
